# Generated by Django 2.0.2 on 2019-01-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FavoriteId', models.CharField(blank=True, max_length=200, null=True)),
                ('bookId', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markerId', models.CharField(blank=True, max_length=200, null=True)),
                ('bookId', models.CharField(blank=True, max_length=200, null=True)),
                ('chapterId', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='author',
            old_name='authorUser',
            new_name='authorName',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authorId',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='recentPlayed',
        ),
        migrations.AddField(
            model_name='author',
            name='authorId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='bookId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='favoriteId',
            field=models.ManyToManyField(blank=True, to='application.Favorite'),
        ),
        migrations.AddField(
            model_name='profile',
            name='markerId',
            field=models.ManyToManyField(blank=True, to='application.Marker'),
        ),
    ]
