# Generated by Django 2.1.5 on 2019-01-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20190117_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authorId',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='markerId',
            new_name='marker',
        ),
        migrations.RemoveField(
            model_name='author',
            name='authorId',
        ),
        migrations.RemoveField(
            model_name='book',
            name='bookId',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='bookId',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='markerId',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favoriteId',
        ),
        migrations.AddField(
            model_name='marker',
            name='book',
            field=models.ManyToManyField(to='application.Book'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite',
            field=models.ManyToManyField(blank=True, to='application.Book'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
