# Generated by Django 2.1.5 on 2019-01-18 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20190117_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='authorName',
        ),
        migrations.RemoveField(
            model_name='book',
            name='authorId',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favoriteId',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='markerId',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Marker',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
