# Generated by Django 2.1.5 on 2019-01-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20190121_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='charpterCount',
            field=models.IntegerField(default=0),
        ),
    ]
