# Generated by Django 2.1.5 on 2019-01-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_book_charptercount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='authorName',
            field=models.CharField(max_length=200),
        ),
    ]
