# Generated by Django 2.1.5 on 2019-01-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20190121_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite',
            field=models.ManyToManyField(to='application.Book'),
        ),
    ]
