# Generated by Django 2.1.5 on 2019-01-26 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20190121_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='book',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
