# Generated by Django 2.1.5 on 2019-01-29 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_book_bookfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['wordCount']},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Author'),
        ),
    ]
