# Generated by Django 2.1.5 on 2019-01-29 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20190129_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='charpterCount',
            new_name='chapterCount',
        ),
    ]
