# Generated by Django 2.1.5 on 2019-01-30 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20190129_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-wordCount']},
        ),
    ]
