# Generated by Django 2.1.5 on 2019-01-30 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_marker_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='book',
        ),
        migrations.AddField(
            model_name='marker',
            name='book',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='application.Book'),
            preserve_default=False,
        ),
    ]
