# Generated by Django 2.1.5 on 2019-01-30 01:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_book_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
