# Generated by Django 2.0.2 on 2019-01-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_book_date_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
