# Generated by Django 2.1.5 on 2019-01-30 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_book_book_image'),
        ('application', '0008_auto_20190129_2046'),
    ]

    operations = [
    ]
