# Generated by Django 2.1.5 on 2019-01-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_merge_20190129_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
