# Generated by Django 2.1.5 on 2019-01-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_auto_20190129_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(default='default_profile.jpg', upload_to='profile_images'),
        ),
    ]
