# Generated by Django 2.1.5 on 2019-01-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_auto_20190130_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(default='default_book.jpg', upload_to='profile_images'),
        ),
    ]
