# Generated by Django 2.1.5 on 2019-01-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_auto_20190130_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite',
            field=models.ManyToManyField(blank=True, to='application.Book'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(default='default_profile.jpg', upload_to='profile_images'),
        ),
    ]
