# Generated by Django 2.1.5 on 2019-01-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_auto_20190130_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookImage',
            field=models.ImageField(blank=True, default='default_book.jpg', upload_to='book_images'),
        ),
    ]
