# Generated by Django 2.1.5 on 2019-02-02 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_auto_20190130_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Book'),
        ),
    ]
