# Generated by Django 2.1.5 on 2019-02-03 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_auto_20190201_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_created_books',
            field=models.IntegerField(default=0),
        ),
    ]
