# Generated by Django 2.1.5 on 2019-02-04 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0029_auto_20190202_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-like', 'chapterCount', 'date_uploaded', '-wordCount']},
        ),
    ]
