# Generated by Django 2.1.5 on 2019-02-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0032_auto_20190206_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookImage',
            field=models.FileField(default='default_book.jpg', upload_to='book_images'),
        ),
    ]
