# Generated by Django 2.1.5 on 2019-02-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0035_auto_20190206_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookFile',
            field=models.FileField(blank=True, null=True, upload_to='book_files'),
        ),
    ]
