# Generated by Django 2.1.5 on 2019-02-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0036_auto_20190206_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='chapterId',
            field=models.CharField(blank=True, help_text='Enter chapter ID and Name would be good', max_length=200, null=True),
        ),
    ]
